name: HomeTeleporter
main: HomeTP\HomeTP
version: 2.0
api: [1.0.0, 2.0.0, 3.0.0]
commands:
 home:
  description: Teleports to your previously set home
  usage: /home <name>
 sethome:
  description: Sets your home
  usage: /sethome <name>
